apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2026-03-21T16:12:46Z"
  labels:
    kubernetes.io/metadata.name: ran-services
  name: ran-services
  resourceVersion: "20149"
  uid: e3d27d6d-0a5c-4c9c-ab85-378c4ff1e2d9
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
