apiVersion: v1
kind: Pod
metadata:
  name: ran-client
  namespace: ran-services
  labels:
    component: gnodeb
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "infinity"]
      resources:
        requests:
          memory: "50Mi"
          cpu: "100m"
        limits:
          memory: "50Mi"
          cpu: "100m"