apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: upf-reader-role
  namespace: user-plane-services
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]